name: Continuous Integration (CI) 
name: Continuous Integration (CI)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    branches: [ "master ]

jobs:
  build:
@@ -13,6 +13,8 @@ jobs:

    steps:
    - uses: actions/checkout@v4
    - name: install-deps
      run: sudo apt-get install libreadline-dev -y
    - name: make
      run: make
    - name: make check
